name: Display Azure
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Display it
      run: |
        echo -n "${{ secrets.WEATHERZILLA_87D6 }}" >> foo && cut -c1-3 foo && cut -c4- foo
